"""LLM response models."""

from __future__ import annotations

from pydantic import Field

from archie.models import ArchieModel


class ChatResponse(ArchieModel):
    """Response generated by an LLM."""

    content: str = Field(
        min_length=1,
    )
